# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms2d', '0003_auto_20161027_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author_id',
            field=models.IntegerField(default=0),
        ),
    ]
